### ISSUE TITLE
ComboBox控件Bug待修复

### ISSUE THREAD

**Issue by Wingsgo** [KD-Group/quite#21]
import quite
w = quite.Widget()
v1 = ['TTL']
v2 = ['LVTTL', 'LVPECL', 'LVDS', 'ECL']
c = quite.ComboBox()
c.string_list.value = v2
w.set_central_widget(c)
w.exec()
c.string_list.value = v1
w.exec()
# 应该显示TTL，结果comboBox显示结果为['TTL', 'LVDS']两个选项

**Comment by SF-Zhou** [comment]
严格来说这不是 BUG。这个 widget 不应该被 `exec` 两次。

**Comment by SF-Zhou** [comment]
我试了下去掉第一次的 exec，也还是有问题。确实是 bug，quina 也有这个 bug。

**Comment by Wingsgo** [comment]
我仔细研究了comboBox的set_value方法并且调试了一下，始终觉得逻辑上没有问题，调试过程中发现当string_list = ['TTL']时，self.count() = 2，这是比较令我迷惑的一点，具体原因还需要调试一下

**Comment by SF-Zhou** [comment]
是我代码的问题。改成：
```python
for index in reversed(range(new_count, old_count)):
    self.removeItem(index)
```
就可以了。`reversed` 很重要。

**Comment by Wingsgo** [comment]
哦，懂了，删除要从最尾端开始删除，不然按照[1， 2， 3]的方式删除的话其实这时候的第3行已经不是原来的第三行了

**Comment by SF-Zhou** [comment]
可以提交个 PR
